### ISSUE TITLE
LWJGL isn't in java.library.path but I'm sure it is

### ISSUE THREAD

**Issue by TheAwesome98-Real** [ManiaDevelopment/Minecraft-Classic-Forever#6]
Exception in thread "Thread-4" java.lang.UnsatisfiedLinkError: no lwjgl in java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at org.lwjgl.Sys$1.run(Sys.java:73)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
        at org.lwjgl.Sys.loadLibrary(Sys.java:95)
        at org.lwjgl.Sys.<clinit>(Sys.java:112)
        at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
        at com.mojang.minecraft.Minecraft.run(Minecraft.java:227)
        at java.lang.Thread.run(Unknown Source)

LWJGL is properly installed in my workspace, so I don't understand why this error happens. The 'MinecraftMania - Single Player' window opens, but it only has the system color background (beige or gray on windows) in it.

**Comment by artdeell** [comment]
> ```
> Exception in thread "Thread-4" java.lang.UnsatisfiedLinkError: no lwjgl in java.library.path
>     at java.lang.ClassLoader.loadLibrary(Unknown Source)
>     at java.lang.Runtime.loadLibrary0(Unknown Source)
>     at java.lang.System.loadLibrary(Unknown Source)
>     at org.lwjgl.Sys$1.run(Sys.java:73)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
>     at org.lwjgl.Sys.loadLibrary(Sys.java:95)
>     at org.lwjgl.Sys.<clinit>(Sys.java:112)
>     at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
>     at com.mojang.minecraft.Minecraft.run(Minecraft.java:227)
>     at java.lang.Thread.run(Unknown Source)
> ```
> 
> LWJGL is properly installed in my workspace, so I don't understand why this error happens. The 'MinecraftMania - Single Player' window opens, but it only has the system color background (beige or gray on windows) in it.

Did you define -Djava.library.path?

**Comment by TheAwesome98-Real** [comment]
I’m not sure, I will check next time I’m on my computer.

**Comment by Mikilis** [comment]
did you linked natives?

**Comment by TheAwesome98-Real** [comment]
Yes i did.

**Comment by TheAwesome98-Real** [comment]
I've got it to work. I switched to Linux lmao

**Comment by TheAwesome98-Real** [comment]
Fuck sake never mind

```
Exception in thread "Thread-2" java.lang.UnsatisfiedLinkError: no lwjgl64 in java.library.path: /usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
        at java.base/java.lang.System.loadLibrary(System.java:1989)
        at org.lwjgl.Sys$1.run(Sys.java:72)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
        at org.lwjgl.Sys.loadLibrary(Sys.java:87)
        at org.lwjgl.Sys.<clinit>(Sys.java:117)
        at org.lwjgl.opengl.Display.<clinit>(Display.java:137)
        at com.mojang.minecraft.Minecraft.run(Minecraft.java:227)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by TheAwesome98-Real** [comment]
wait actually i use vscode now so the natives might not be added

**Comment by TheAwesome98-Real** [comment]
I'm setting `java.library.path` like this: `-Djava.library.path="run/native/*:${system_property:java.library.path}"` in my `./startclient.sh`, but then I get a similar exception: `no lwjgl64 in java.library.path: run/native/*:`

It isn't adding back the rest of the path, and also still isn't finding LWJGL natives

**Comment by TheAwesome98-Real** [comment]
I've solved it not having the default path but the issue is still ther
