### ISSUE TITLE
java.lang.IllegalArgumentException: input == null!

### ISSUE THREAD

**Issue by PeytonPlayz595** [ManiaDevelopment/Minecraft-Classic-Forever#7]
When running in eclipse I get this error

```java
java.lang.IllegalArgumentException: input == null!
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1358)
	at com.mojang.minecraft.gui.FontRenderer.<init>(FontRenderer.java:24)
	at com.mojang.minecraft.Minecraft.run(Minecraft.java:307)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

This is the code in FontRenderer.java that causes the error:

```java
BufferedImage var14;
try {
     var14 = ImageIO.read(TextureManager.class.getResourceAsStream(var2));
} catch (IOException var13) {
     throw new RuntimeException(var13);
}
```

var2 is a string set to file names like "/default.png", "/default.gif", etc

**Comment by TheAwesome98-Real** [comment]
i'm pretty sure that means it could not open the file

**Comment by PeytonPlayz595** [comment]
I added all of the resource file in the "bin" folder along with all the class files and the error did not appear

**Comment by TheAwesome98-Real** [comment]
so can this be closed?

**Comment by PeytonPlayz595** [comment]
Yeah
